export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QTY = "ADJUST_QTY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const GET_MENUITEMS_REQUEST = "GET_MENUITEMS_REQUEST";
export const GET_MENUITEMS_SUCCESS = "GET_MENUITEMS_SUCCESS";
export const GET_MENUITEMS_FAILURE= "GET_MENUITEMS_FAILURE";
